### ISSUE TITLE
New hope

### ISSUE THREAD

**Issue by ghost** [hbtlabs/chromium#4]
Hello,

Thank you very much for your effort!
There's a new Issue on Chromium side regarding this problem: [https://bugs.chromium.org/p/chromium/issues/detail?id=1130191](https://bugs.chromium.org/p/chromium/issues/detail?id=1130191)
If you have time, could you please throw your 2 cents in?

Best regards!

**Comment by hbt** [comment]
Thank you for notifying me.
I don't upgrade to latest chrome version unless I'm certain there are no regressions on this issue. 


Regarding the logged issue https://bugs.chromium.org/p/chromium/issues/detail?id=1130191 

I'd recommend focusing on being constructive. There are most likely no automated tests to detect this regression and it's expected to come back. I don't know your technical expertise but if I were you; I would:

- record it on video and post it on youtube with the chrome version (google-chrome vs chromium and exact built version and platform). Depending on where the bug is located it could be different developers that introduced.

- Report the exact last version when this used to work. This will help pin down the source of the change and identify it as a regression.

- Mention the big ticket that worked on this and do some research in the bug tracker for the recent regressions. As mentioned above, it could be an unrelated change.

- If you identified the exact line in the source code, mention it in the ticket and even better push a quick fix like I did. It helps developers quickly reproduce the ticket and see the before/after even if the pull request solution won't be merged.

- Build a Dockerfile with chrome properly configured to reproduce the bug so developers can simply fire it up and reproduce the issue. view https://github.com/hbt/dockerfile-ubuntu-mate-tigervnc as an example 

- Contact directly the people who cared about this issue and point them to your new ticket if none of the above worked.

- Contact the developers who fixed the issue / regressions and  get feedback.


Most importantly, I don't know if you're the ticket submitter but do not attack developers by calling them incompetent. I understand your frustration but it just sets the wrong tone on the ticket and when people start piling up with toxic attack, ticket gets flagged as noise, developers unsubscribe from notifications and move on.
I would recommend creating another ticket altogether under a different account with the information detailed above.


As you can see, it takes work and time. I will be upgrading next quarter, if there is an issue, I will do the work above or go back to an older version.


Best of luck and feel free to keep posting here about your progress. People do read.

**Comment by ispeaknousa** [comment]
Hello,

Thank you for your time and the insights!
I am the culprit, and while it's true that toxicity raises more toxicity, maybe some personal frustration will raise the attention to user needs (I really like the way Chrome is loading the pages and don't want to quit using it). I do hope they don't take it personally, though.

I don't know if Chromium ticket tracking includes testers or if developers pick up tickets. If it's the first case, you are right with all the points from above, but if the developer is the one who takes the ticket, then a look through the code would definitely help more then requiring proof from users stating that "it doesn't work on my machine" (albeit docker).

Nonetheless. A part of me sees it exactly like you do (hence the frustration)...
I really appreciate your effort and findings, and will take your advice with all the points from the list.
Thank you again for you're time and constructive attitude!
I'll return once everything is sorted out, one way (issue fixed upstream) or the other (patch). :)

**Comment by ghost** [comment]
Hello,

Thank you for your time and the insights!
I am the culprit, and I know, it's true that toxicity raises more toxicity... That's why things shouldn't be written/spoken while the blood is still boiling.

I really appreciate your effort and findings, and will take your advice with all the points from the list.
Thank you again for you're time and constructive attitude!
I'll return once everything is sorted out, one way (issue fixed upstream) or the other (patch). :)

**Comment by hbt** [comment]
@ispeaknousa I've tested it with Version 87.0.4280.66 (Official Build) (64-bit)

There is a white flash but there is a workaround if you do the following:

- install dark reader https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh?hl=en
- install dark theme https://chrome.google.com/webstore/detail/just-black/aghfnjkcakhmadgdomlmlhhaocbkloab
- enable these config flags in chrome://flags/ : 
    - Force Dark Mode for Web Contents
    - Web Platform Controls Dark Mode


If you do that, there is no white flash.

Will be closing this, feel free to reopen if you encounter further issues.

Thanks
